"""
Shared pytest fixtures for the orchestrator test suite.

All fixture CSVs live in `tests/fixtures/` and are committed to git so
they double as example payloads for factory-test calls. They are
generated by `tests/fixtures/_generate.py` if they ever need to be
rebuilt.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

# Make sure PCIL_dev/ is on sys.path so `from pcil.orchestrator import app`
# resolves regardless of where pytest was invoked from.
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

# Path to committed fixture CSVs. Tests open these directly when sending
# multipart uploads.
FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures"


@pytest.fixture
def shop_floor_tiny_path() -> Path:
    """Tiny shop-floor CSV (50 rows) matching the inkjet_printer
    config.yaml schema. Realistic enough for the full pipeline
    (preprocess -> adapter -> LinearRegression) to fit cleanly."""
    return FIXTURE_DIR / "shop_floor_tiny.csv"


@pytest.fixture
def cyclical_tiny_path() -> Path:
    """Tiny cyclical CSV (50 rows). Has machine_id / timestamp /
    signal_value columns but is too short for peak-based cycle
    detection — tests that exercise the real training path
    monkeypatch it instead."""
    return FIXTURE_DIR / "cyclical_tiny.csv"


@pytest.fixture
def non_cyclical_clean_tiny_path() -> Path:
    """50 rows of acoustic-style 'clean' recording (low-amplitude
    Gaussian noise on Acceleration 0/1/2 + AE)."""
    return FIXTURE_DIR / "non_cyclical_clean_tiny.csv"


@pytest.fixture
def non_cyclical_anomaly_tiny_path() -> Path:
    """50 rows of acoustic-style 'anomaly' recording (higher-amplitude
    noise — distinguishable from clean even after feature extraction)."""
    return FIXTURE_DIR / "non_cyclical_anomaly_tiny.csv"


@pytest.fixture
def app():
    """Import the orchestrator inside the fixture so other fixtures
    (e.g. isolated_data_dir) can override env / module-level vars
    before the app is instantiated."""
    from pcil.orchestrator import app as _app
    return _app


@pytest.fixture
def client(app) -> TestClient:
    """FastAPI TestClient — wraps the app in an in-process HTTP server.
    Use client.post(...) / client.get(...) the same way you would with
    requests."""
    return TestClient(app)


@pytest.fixture
def isolated_data_dir(monkeypatch, tmp_path) -> Path:
    """Redirect PROJECT_ROOT so any bundle the orchestrator saves
    (via /anomaly/train) lands in a per-test tmp dir, not the real
    `ITP/data/` folder.

    Returns the tmp data/ path so tests can assert bundle presence.
    """
    data_dir = tmp_path / "data"
    data_dir.mkdir()

    import pcil.orchestrator as orch
    monkeypatch.setattr(orch, "PROJECT_ROOT", tmp_path)
    return data_dir
